pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'Architectury'
            url = 'https://maven.architectury.dev/'
        }
        maven {
            name = 'FabricMC'
            url = 'https://maven.fabricmc.net/'
        }
    }
}

include('common', 'forge', 'fabric')
rootProject.name = 'BotzGuildz'
